### ISSUE TITLE
[FEATURE] Add Stryker Mutation Testing to CI Pipeline

### ISSUE THREAD

**Issue by AndrewBarber** [Space48/mutation-ready#2]
**Is your feature request related to a problem? Please describe.**
We currently lack comprehensive test coverage validation in our CI pipeline. While our unit tests verify basic functionality, we don't have a way to assess the quality and effectiveness of our test suite systematically.

**Describe the solution you'd like**
Integrate Stryker Mutation Testing into our CI pipeline to:
- Run mutation tests automatically on pull requests
- Set a minimum mutation score threshold (80%)
- Generate and store mutation test reports as artifacts
- Add mutation score badges to our README

**Example Usage**
```yaml
jobs:
  mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npx stryker run
```

**Additional context**
Current mutation score: 77.27%
Target mutation score: 80%+
